apiVersion: apps/v1
kind: Deployment 
metadata:
  name: usermgmt-webapp
  labels:
    app: usermgmt-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-webapp
  template:  
    metadata:
      labels: 
        app: usermgmt-webapp
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.36
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']      
      containers:
        - name: usermgmt-webapp
          image: phpmyadmin/phpmyadmin:5.2
          imagePullPolicy: Always
          ports: 
            - containerPort: 80           
          env:
            - name: PMA_HOST
              value: "mysql"            
            - name: PMA_PORT
              value: "3306"            
            - name: PMA_USER
              value: "root"            
            - name: PMA_PASSWORD
              value: "dbpassword11"
            - name: MYSQL_ROOT_PASSWORD
              value: "dbpassword11"
